title: Game Design and Development
description: The official website for the Game Design and Development Decal at UC Berkeley.
theme: just-the-docs
color_scheme: wider

url: https://berkeleyGamedev.github.io/DecalWebsite

# logo: "gdd-logo-full.png"