title: Game Design and Development Decal
description: The official website for the Game Design and Development Decal at UC Berkeley.
theme: just-the-docs

url: https://berkeleyGamedev.github.io/DecalWebsite
